name: Continuous Deployment

on:
  push:
    branches:
      - CI/CD-experimentation
jobs:  
  deploy-test:
    runs-on: ubuntu-latest      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run stress API tests
      run: make stress-test

  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIAL_JSON}}

    - name: Authenticate Docker with GCR
      run: docker login -u _json_key --password-stdin https://gcr.io
  
    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest .

    - name: Push Docker image to GCR
      run: docker push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest .
