name: Continuous Deployment

on:
  push:
    branches:
      - CI/CD-experimentation
jobs:  
  deploy-test:
    runs-on: ubuntu-latest      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run stress API tests
      run: make stress-test
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIAL_JSON}}
